title: Project
pages: false
options:
  template: false
files:
	sortable: true
fields:
	title:
		label: Title
    type:  text
  year:
    label: Year
    type:  text
  color:
    label: Color
    type:  select
    width: 1/2
    options:
      blue: Blue
      yellow: Yellow
      red: Red
  website:
    label: Website
    type:  text
  tagline:
    label: Tagline
    type:  text
  challenge:
    label: The Challenge
    type:  text
    width: 1/2
  role:
    label: My Role
    type:  text
    width: 1/2
  isPasswordProtected:
    label: Protection
    type:  checkbox
	text:
		label: Content
		type:  textarea
