name: CI

on:
  push:
    branches: main
    paths:
      [
        "src/components/**",
        "src/helpers/**",
        "src/layouts/**",
        "src/pages/**",
        "src/stores/**",
        "playwright.config.ts",
        "astro.config.mjs",
        ".htmlvalidate.json",
      ]
  pull_request:
    branches: main
    paths:
      [
        "src/components/**",
        "src/helpers/**",
        "src/layouts/**",
        "src/pages/**",
        "src/stores/**",
        "playwright.config.ts",
        "astro.config.mjs",
        ".htmlvalidate.json",
      ]

jobs:
  test:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Install Playwright
        run: pnpm exec playwright install chromium

      - name: Run Playwright tests
        run: pnpm test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  html-validate:
    name: HTML5 Validation
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Build and validate HTML5
        run: pnpm html-validate
