name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Run once a week
    - cron: "0 0 * * 0"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: "--no-progress --config .lychee.toml ."

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: automated
