name: Playwright
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Vercel Preview URL
        uses: zentered/vercel-preview-url@v1.1.9
        with:
          vercel_project_id: "prj_pMk8EbUuHxsj51ERiVXZyANy9ZPC"
      - name: Run Playwright tests
        run: npx playwright test --project="Google Chrome"
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.deployment.target_url || 'https://evadecker.com' }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
