name: Playwright
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      # If you're NOT going to use `--project="Google Chrome"` when running
      # the Playwright tests, uncomment these lines. They're very slow
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      - name: Wait for 200 from the Netlify Preview
        # Only wait for Netlify Preview if not deploying to production
        if: github.ref != 'refs/heads/main'
        uses: JakePartusch/wait-for-netlify-action@v1.4
        id: netlify
        with:
          site_name: "evadecker"
      - name: Run Playwright tests
        run: npx playwright test --project="Google Chrome"
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.netlify.outputs.url || 'https://evadecker.com' }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
