name: HTML5 Validation
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  html-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages
        run: pnpm i
      - name: Build and validate HTML5
        run: pnpm html-validate
